### PR TITLE
Unify and speed up data ingestion

### PR DESCRIPTION
**Pull request by dvukolov**
The following set of patches unifies handling of X covariates supplied by the Python package. Instead of treating it as a special case in C code, the data is converted to the expected column-major (Fortran, R) order in Python.

Additionally, the updated C code aims to reuse existing memory blocks of X and Y, instead of copying them to Eigen Arrays. This lowers memory usage and speeds up processing of large inputs.

I also took the liberty to remove the cutils.py file. Required checks for contiguous order of arrays are still performed, while the code is much simpler to maintain.

Please let me know if theses patches need any changes. I am more than willing to adapt them to your requirements. Many thanks!

### CODE REVIEW

**Comment by jasonge27** [comment]
Hi Dmitry, thanks a lot for helping us improve the software! Can you run the scripts in the profiling folder and paste the results and your profiling environment here?

**Comment by dvukolov** [comment]
Hi Jason, here is the output from the scripts and their respective environments. Tell me If you need any additional information on the environment or extra tests. 

<details><summary>benchmark.R</summary>

```
Loading required package: glmnet
Loading required package: Matrix
Loading required package: foreach
Loaded glmnet 2.0-16

Loading required package: picasso
Loading required package: MASS
Loading required package: ncvreg
Loading required package: scalreg
Loading required package: lars
Loaded lars 1.2

Loading required package: flare
Loading required package: lattice
Loading required package: igraph

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union


-----------------------------------------------------------

-----------------------------------------------------------
-------Testing Linear Regression with L1 Penalty------
------Comparisions of estimation errors.------
-----------------------
---------n=500, p=5000, c=0.25---------
picasso
time,0.0790000000000006,std,0.0028284271247396,
obj,21.133894642965,std,0,
glmnet
time,0.214500000000005,std,0.00353553390593455,
obj,21.1121958930965,std,0,
ncvreg
time,0.269000000000002,std,0.00141421356237482,
obj,21.1133159829268,std,0,
-----------------------
---------n=1000, p=10000, c=0.25---------
picasso
time,0.29849999999999,std,0.00919238815544891,
obj,24.0210728964651,std,0,
glmnet
time,0.700000000000017,std,0.00141421356237985,
obj,24.013223046184,std,0,
ncvreg
time,0.900000000000006,std,0.00282842712479989,
obj,24.0121999123824,std,0,
---------n=500, p=5000, c=0.75---------
picasso
time,0.152999999999992,std,0.00141421356237985,
obj,29.664318720043,std,0,
glmnet
time,0.382000000000005,std,0,
obj,29.6576534429879,std,0,
ncvreg
time,0.331999999999994,std,0,
obj,29.6536940794226,std,0,
-----------------------
---------n=1000, p=10000, c=0.75---------
picasso
time,0.600999999999999,std,0.00141421356233965,
obj,30.2644547114185,std,0,
glmnet
time,1.52949999999998,std,0.00494974746834956,
obj,30.2593287135737,std,0,
ncvreg
time,1.20049999999998,std,0.0318198051533657,
obj,30.2566777520088,std,0,

-----------------------------------------------------------

-----------------------------------------------------------
-------Testing Linear Regression with SCAD/MCP Penalty------
-----------------------
---------n=500, p=5000, c=0.25---------
picasso
time,0.0819999999999936,std,0,
obj,20.6273398986348,std,0,
ncvreg
time,0.392500000000041,std,0.000707106781169827,
obj,20.6096976460603,std,0,
-----------------------
---------n=1000, p=10000, c=0.25---------
picasso
time,0.317999999999984,std,0.00565685424968017,
obj,23.8153490165114,std,0,
ncvreg
time,1.303,std,1.60777467769219e-13,
obj,23.8085227079811,std,0,
---------n=500, p=5000, c=0.75---------
picasso
time,0.152999999999906,std,0.00141421356250043,
obj,29.664318720043,std,0,
ncvreg
time,0.33299999999997,std,1.60777467769219e-13,
obj,29.6536940794226,std,0,
-----------------------
---------n=1000, p=10000, c=0.75---------
picasso
time,0.598499999999945,std,0.00494974746818879,
obj,30.2644547114185,std,0,
ncvreg
time,1.22149999999999,std,0.0205060966542465,
obj,30.2566777520088,std,0,

-----------------------------------------------------------

-----------------------------------------------------------
-------Testing Logistic Regression with L1 Penalty------
------Comparisions of estimation errors.------
-----------------------
---------n=500, p=2000, c=0.25---------
picasso
time,0.0819999999999936,std,1.60777467769219e-13,
obj,0.346384839960476,std,0,
glmnet
time,0.221499999999992,std,0.000707106781169827,
obj,0.346365978722111,std,0,
ncvreg
time,0.159000000000106,std,0,
obj,0.346365990982529,std,0,
-----------------------
---------n=1000, p=5000, c=0.25---------
picasso
time,0.336499999999887,std,0.000707106781330604,
obj,0.363342664385665,std,0,
glmnet
time,1.02750000000003,std,0.00353553390584913,
obj,0.363334573155926,std,0,
ncvreg
time,0.472499999999854,std,0.00494974746834956,
obj,0.363334719059611,std,0,
---------n=500, p=2000, c=0.75---------
picasso
time,0.0720000000000027,std,1.60777467769219e-13,
obj,0.325015944515103,std,0,
glmnet
time,0.378999999999905,std,0,
obj,0.324990507426659,std,0,
ncvreg
time,0.265499999999975,std,0.000707106781330604,
obj,0.324991115053388,std,0,
-----------------------
---------n=1000, p=5000, c=0.75---------
picasso
time,0.323499999999854,std,0.000707106781169827,
obj,0.335219659495985,std,0,
glmnet
time,1.83749999999998,std,0.000707106781169827,
obj,0.335183142848065,std,0,
ncvreg
time,1.79999999999984,std,0.0169705627485582,
obj,0.335185463223221,std,0,

-----------------------------------------------------------

-----------------------------------------------------------
-------Testing Logistic Regression with SCAD/MCP Penalty------
-----------------------
---------n=500, p=2000, c=0.25---------
picasso
time,0.015999999999849,std,0,
obj,0.25931467714238,std,0,
ncvreg
time,0.0880000000001928,std,0,
obj,0.313532423422571,std,0,
-----------------------
---------n=1000, p=5000, c=0.25---------
picasso
time,0.0650000000000546,std,0.00141421356233965,
obj,0.220816355827308,std,0,
ncvreg
time,0.273500000000013,std,0.0021213203433487,
obj,0.271318595778008,std,0,
-----------------------
---------n=500, p=2000, c=0.75---------
picasso
time,0.0144999999999982,std,0.000707106781009049,
obj,0.181838261969391,std,0,
ncvreg
time,0.169999999999845,std,0.00282842712467931,
obj,0.252802822242484,std,0,
-----------------------
---------n=1000, p=5000, c=0.75---------
picasso
time,0.0650000000000546,std,0,
obj,0.180159694740963,std,0,
ncvreg
time,1.72250000000008,std,0.000707106781330604,
obj,0.275255849790363,std,0,

-----------------------------------------------------------
-------Testing Square Root Lasso------
-----------------------
---------n=200, p=1000, c=0.25---------
picasso
time,5.62399999999991,std,0.065053823869071,
obj,2.70256487359964,std,0,
flare
time,2.03649999999982,std,0.00212132034350948,
obj,3.33596766724413,std,0,
scalreg
time,1.24799999999993,std,0.0678822509940719,
obj,2.8674836077163,std,0,
-----------------------
---------n=500, p=2000, c=0.25---------
picasso
time,0.112999999999943,std,0.00141421356250043,
obj,4.51453032009697,std,0,
flare
time,9.23149999999998,std,0.333047293938706,
obj,5.18816498881372,std,0,
scalreg
time,40.631,std,0.0806101730554503,
obj,4.49215068065684,std,0,
-----------------------
---------n=200, p=1000, c=0.75---------
picasso
time,0.0270000000000437,std,0,
obj,5.39819128705506,std,0,
flare
time,29.1795000000001,std,0.321733585439988,
obj,5.9791077210624,std,0,
scalreg
time,3.80600000000004,std,0.340825468531895,
obj,5.39492759213467,std,0,
---------n=500, p=2000, c=0.75---------
picasso
time,0.119500000000016,std,0.000707106781009049,
obj,5.51133275282837,std,0,
flare
time,466.306,std,2.66437835151093,
obj,5.95891717019304,std,0,
scalreg
time,44.1595,std,0.710642315092879,
obj,5.50700883793684,std,0,
```
</details>

<details><summary>benchmark.py</summary>

```
Training is over.
Testing L1 penalized linear regression, number of samples:500, sample dimension:200, correlation:0.100000
Picasso time:0.020191, Obj function value:18229.087693
Sklearn time:0.131272, Obj function value:18215.889024
Training is over.
Testing L1 penalized linear regression, number of samples:500, sample dimension:400, correlation:0.100000
Picasso time:0.030454, Obj function value:31333.739540
Sklearn time:0.438581, Obj function value:31299.350801
Training is over.
Testing L1 penalized linear regression, number of samples:500, sample dimension:600, correlation:0.100000
Picasso time:0.043958, Obj function value:33200.776489
Sklearn time:2.312127, Obj function value:33142.578552
Training is over.
Testing L1 penalized linear regression, number of samples:500, sample dimension:800, correlation:0.100000
Picasso time:0.054918, Obj function value:46581.492775
Sklearn time:3.858857, Obj function value:46468.483452
Training is over.
Testing L1 penalized linear regression, number of samples:500, sample dimension:1000, correlation:0.100000
Picasso time:0.071455, Obj function value:37635.203858
Sklearn time:7.809720, Obj function value:37505.726739
Training is over.
Testing L1 penalized linear regression, number of samples:500, sample dimension:200, correlation:0.100000
Picasso time:0.038301, Obj function value:0.389599
Sklearn time:1.219515, Obj function value:0.389598
Training is over.
/usr/local/lib/python3.7/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
Testing L1 penalized linear regression, number of samples:500, sample dimension:400, correlation:0.100000
Picasso time:0.053749, Obj function value:0.346706
Sklearn time:2.158921, Obj function value:0.346700
Training is over.
Testing L1 penalized linear regression, number of samples:500, sample dimension:600, correlation:0.100000
Picasso time:0.067185, Obj function value:0.363429
Sklearn time:3.127010, Obj function value:0.363420
Training is over.
/usr/local/lib/python3.7/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
Testing L1 penalized linear regression, number of samples:500, sample dimension:800, correlation:0.100000
Picasso time:0.077130, Obj function value:0.335014
Sklearn time:4.106001, Obj function value:0.335002
Training is over.
/usr/local/lib/python3.7/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
Testing L1 penalized linear regression, number of samples:500, sample dimension:1000, correlation:0.100000
Picasso time:0.094702, Obj function value:0.348818
Sklearn time:4.992054, Obj function value:0.348806
```
</details>

<details><summary>R environment</summary>

```
> library(glmnet); library(picasso); library(ncvreg); library(scalreg); library(flare); sessionInfo()
Loading required package: Matrix
Loading required package: foreach
Loaded glmnet 2.0-16

Loading required package: MASS
Loading required package: lars
Loaded lars 1.2

Loading required package: lattice
Loading required package: igraph

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union

R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux buster/sid

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] flare_1.6.0     igraph_1.2.2    lattice_0.20-38 scalreg_1.0    
 [5] lars_1.2        ncvreg_3.11-0   picasso_1.1.0   MASS_7.3-51.1  
 [9] glmnet_2.0-16   foreach_1.4.4   Matrix_1.2-15  

loaded via a namespace (and not attached):
[1] compiler_3.5.2   magrittr_1.5     codetools_0.2-16 grid_3.5.2      
[5] iterators_1.0.10 pkgconfig_2.0.2 
```
</details>

<details><summary>Python environment</summary>

```
>>> import sklearn; sklearn.show_versions()
ATLAS version 3.10.3 built by buildd on Tue Jan 17 22:59:14 UTC 2017:
   UNAME    : Linux x86-ubc-01 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
   INSTFLG  : -1 0 -a 1 -l 1
   ARCHDEFS : -DATL_OS_Linux -DATL_ARCH_x86SSE2 -DATL_CPUMHZ=2297 -DATL_SSE2 -DATL_SSE1 -DATL_USE64BITS -DATL_GAS_x8664
   F2CDEFS  : -DAdd_ -DF77_INTEGER=int -DStringSunStyle
   CACHEEDGE: 1048576
   F77      : /usr/bin/x86_64-linux-gnu-gfortran, version GNU Fortran (Debian 6.3.0-2) 6.3.0 20161229
   F77FLAGS : -fomit-frame-pointer -mfpmath=sse -O2 -msse2 -fPIC -m64
   SMC      : /usr/bin/gcc-6, version gcc-6 (Debian 6.3.0-2) 6.3.0 20161229
   SMCFLAGS : -fomit-frame-pointer -mfpmath=sse -O2 -msse2 -fPIC -m64
   SKC      : /usr/bin/gcc-6, version gcc-6 (Debian 6.3.0-2) 6.3.0 20161229
   SKCFLAGS : -fomit-frame-pointer -mfpmath=sse -O2 -msse2 -fPIC -m64

System:
    python: 3.7.1 (default, Nov 16 2018, 22:26:09)  [GCC 6.3.0 20170516]
executable: /usr/local/bin/python
   machine: Linux-4.15.0-43-generic-x86_64-with-debian-9.6

BLAS:
    macros: HAVE_CBLAS=None, ATLAS_INFO="\"3.10.3\""
  lib_dirs: /usr/lib/atlas-base
cblas_libs: f77blas, cblas, atlas, f77blas, cblas

Python deps:
       pip: 18.1
setuptools: 40.6.2
   sklearn: 0.20.2
     numpy: 1.15.4
     scipy: 1.2.0
    Cython: None
    pandas: None
```
</details>

**Comment by jasonge27** [comment]
Merged, thanks a lot Dimitry @dvukolov !

**Comment by dvukolov** [comment]
Glad I could be of service 👍Thanks for the amazing library!

**Pull request merged**
